.PHONY: docs

docs:
	jazzy \
		--clean \
		--author "Ringly" \
		--author_url "http://ringly.com" \
		--github_url "https://github.com/ringly/ios" \
		--github-file-prefix "https://github.com/ringly/ios/tree/development/RinglyAPI/" \
		--module-version "1.0" \
		--xcodebuild-arguments -scheme,RinglyAPI \
		--module RinglyAPI \
		--output Documentation \
