#import <Foundation/Foundation.h>
#import "RLYDefines.h"

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Activity Tracking Date Errors

/**
 *  The domain for errors generated by `RLYActivityTrackingDate`.
 */
RINGLYKIT_EXTERN NSString *const RLYActivityTrackingDateErrorDomain;

/**
 *  Enumerates the codes for errors generated by `RLYActivityTrackingDate`.
 */
typedef NS_ENUM(NSInteger, RLYActivityTrackingDateErrorCode)
{
    /**
     *  The interval provided was greater than the maximum allowable value.
     */
    RLYActivityTrackingDateErrorCodeIntervalGreaterThanMaximum,

    /**
     *  The interval provided was less than the maximum allowable value.
     */
    RLYActivityTrackingDateErrorCodeIntervalLessThanMinimum
};

/**
 *  A user info key containing the invalid interval.
 */
RINGLYKIT_EXTERN NSString *const RLYActivityTrackingDateInvalidIntervalKey;

/**
 *  A user info key containing the invalid timestamp.
 */
RINGLYKIT_EXTERN NSString *const RLYActivityTrackingDateInvalidTimestampKey;

NS_ASSUME_NONNULL_END
