.PHONY: docs

docs:
	jazzy \
	  --objc \
	  --clean \
	  --author Ringly \
	  --author_url https://ringly.com \
	  --github_url https://github.com/ringly/RinglyKit \
	  --github-file-prefix https://github.com/ringly/RinglyKit/tree/development \
	  --module-version 1.0 \
	  --umbrella-header RinglyKit/RinglyKit.h \
	  --framework-root . \
	  --module RinglyKit \
	  --output Documentation