#!/usr/bin/env bash

xcodebuild -workspace "$(dirname $0)/../Ringly.xcworkspace" -scheme Ringly clean build OTHER_SWIFT_FLAGS="-Xfrontend -debug-time-function-bodies" | grep .[0-9]ms | grep -v ^0.[0-9]ms | sort -nr
