#!/usr/bin/env bash

set -e
set -u

echo "Building with configuration “${CONFIGURATION}” and provisioning profile ${PROVISIONING_PROFILE}"

# the directory containing the Xcode workspace
WORKSPACE_DIRECTORY="$(dirname "$0")/.."

# run the bootstrapping script, to build Carthage frameworks
"$WORKSPACE_DIRECTORY/Tools/bootstrap"

# set the build version if specified
if [ -z ${BUILD_NUMBER+null} ]; then
    echo "No build number set. This is okay - will build without modifying “Info.plist” or badging icon."
else
    /usr/libexec/PlistBuddy -c "Set CFBundleVersion ${BUILD_NUMBER}" "${WORKSPACE_DIRECTORY}/Ringly/Ringly/Ringly-Info.plist"

    # badge the icon files with information
    HASH=`/usr/bin/git rev-parse --short HEAD`
    VERSION=`/usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" "${WORKSPACE_DIRECTORY}/Ringly/Ringly/Ringly-Info.plist"`

    for line in $(find Ringly/Ringly/Images.xcassets/AppIcon.appiconset -iname "*.png"); do
      WIDTH=`/usr/local/bin/identify -format %w ${line}`
      HEIGHT=`/usr/local/bin/identify -format %h ${line}`
      START_Y=`expr ${HEIGHT} - ${HEIGHT} \* 2 / 5`
      POINTSIZE=`expr ${HEIGHT} / 6`

      /usr/local/bin/mogrify \
        -fill 'rgba(0,0,0,0.5)' \
        -draw "rectangle 0,${START_Y} ${WIDTH},${HEIGHT}" \
        -fill 'rgb(255, 255, 255)' \
        -font '/Library/Fonts/Arial.ttf' \
        -pointsize ${POINTSIZE} \
        -antialias \
        -gravity South \
        -draw "text 0,0 '${HASH}'" \
        -gravity North \
        -draw "text 0,${START_Y} '${VERSION} • #${BUILD_NUMBER}'" \
        ${line}
    done
fi

# create temporary directories for builds
BUILD_DIRECTORY=$(mktemp -d)
ARCHIVE_DIRECTORY=$(mktemp -d)
DERIVED_DATA_DIRECTORY=$(mktemp -d)
ARCHIVE_PATH="${ARCHIVE_DIRECTORY}/Ringly.xcarchive"
IPA_PATH="${ARCHIVE_DIRECTORY}/Ringly.ipa"

echo "Building in $BUILD_DIRECTORY"
echo "Archiving in $ARCHIVE_DIRECTORY"
echo "Derived Data in $DERIVED_DATA_DIRECTORY"

# build the app
/usr/bin/xcodebuild \
  -scheme Ringly \
  -workspace "${WORKSPACE_DIRECTORY}/Ringly.xcworkspace" \
  -configuration "${CONFIGURATION}" \
  -derivedDataPath "${DERIVED_DATA_DIRECTORY}" \
  archive \
  -archivePath "${ARCHIVE_PATH}" \
  "CONFIGURATION_BUILD_DIR=${BUILD_DIRECTORY}"

/usr/bin/xcodebuild \
  -exportArchive \
  -archivePath "${ARCHIVE_PATH}" \
  -exportPath "${IPA_PATH}" \
  -exportFormat ipa \
  -exportProvisioningProfile "${PROVISIONING_PROFILE}"

# zip up the dsym
cd "${BUILD_DIRECTORY}"
DSYM_ZIP_PATH="${BUILD_DIRECTORY}/Ringly.app.dSYM.zip"
zip -r "$DSYM_ZIP_PATH" *.dSYM

echo "IPA is at $IPA_PATH, zipped dSYM is at $DSYM_ZIP_PATH"

# if we have hockeyapp information specified, upload to hockeyapp
if [ -z ${HOCKEYAPP_APP+null} ] && [ -z ${HOCKEYAPP_TOKEN+null} ]; then
    echo "HockeyApp information not provided - will not upload to HockeyApp"
else
    CHANGES=$(git --git-dir="${WORKSPACE_DIRECTORY}/.git" log --pretty="* `%h` *%an*: %s" ${GIT_PREVIOUS_COMMIT}..${GIT_COMMIT})

    curl \
        -F "status=2" \
        -F "notify=0" \
        -F "mandatory=0" \
        -F "notes=#Ringly
This build is number ${BUILD_NUMBER}.
#Changes
$CHANGES" \
        -F "notes_type=1" \
        -F "ipa=@${IPA_PATH}" \
        -F "dsym=@${DSYM_ZIP_PATH}" \
        -H "X-HockeyAppToken: ${HOCKEYAPP_TOKEN}" \
        "https://rink.hockeyapp.net/api/2/apps/${HOCKEYAPP_APP}/app_versions/upload"
fi
